# Generated by Django 2.1.7 on 2019-02-14 09:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('gambar', models.ImageField(default='', max_length=255, upload_to='')),
                ('isi', models.TextField()),
                ('kontributor', models.CharField(max_length=255)),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('comment', models.CharField(default='0', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='berita',
            name='kategori',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='berita.Kategori'),
        ),
    ]
