# Generated by Django 2.1.7 on 2019-02-14 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ekonomi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('gambar', models.ImageField(default='', max_length=255, upload_to='')),
                ('isi', models.TextField()),
                ('kontributor', models.CharField(max_length=255)),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('comment', models.CharField(default='0', max_length=25)),
                ('kategori', models.CharField(default='ekonomi', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='OlahRaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('gambar', models.ImageField(default='', max_length=255, upload_to='')),
                ('isi', models.TextField()),
                ('kontributor', models.CharField(max_length=255)),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('comment', models.CharField(default='0', max_length=25)),
                ('kategori', models.CharField(default='olah raga', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Otomotif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('gambar', models.ImageField(default='', max_length=255, upload_to='')),
                ('isi', models.TextField()),
                ('kontributor', models.CharField(max_length=255)),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('comment', models.CharField(default='0', max_length=25)),
                ('kategori', models.CharField(default='otomotif', max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='berita',
            name='kategori',
            field=models.CharField(default='berita', max_length=25),
        ),
        migrations.DeleteModel(
            name='Kategori',
        ),
    ]
